---
- hosts: webserver
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Ensure Python3 and pip
    # adjust for your OS; this example is Debian/Ubuntu
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ run_user | default('ubuntu') }}"
        mode: '0755'

    - name: Copy application files
      copy:
        src: ../app/
        dest: "{{ app_dir }}/"
        owner: "{{ run_user | default('ubuntu') }}"
        mode: '0644'

    - name: Install requirements
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        executable: pip3

    - name: Deploy systemd service
      template:
        src: templates/app.service.j2
        dest: "/etc/systemd/system/{{ service_name }}.service"
        mode: '0644'

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable & restart app service
      systemd:
        name: "{{ service_name }}"
        state: restarted
        enabled: yes

