---
- hosts: webserver
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure Python3 and pip
      apt:
        name: ["python3", "python3-pip"]
        state: present
        update_cache: yes

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: "0755"

    - name: Copy application files
      copy:
        src: "../app/"
        dest: "{{ app_dir }}"
        mode: "0755"

    - name: Install requirements
      pip:
        requirements: "{{ app_dir }}/requirements.txt"

    - name: Deploy systemd service
  template:
    src: templates/app.service.j2
    dest: "{{ service_unit_path }}"
    mode: '0644'
  become: yes

- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: Enable & restart app service
  systemd:
    name: "{{ service_name }}"
    state: restarted
    enabled: yes
  become: yes

